### ISSUE TITLE
Change language of prelabel

### ISSUE THREAD

**Issue by Greekcoins** [nomisma/framework#34] opened 2019-04-17 13:53 UTC
Cahnging the language of a preflabel for an Id that has multiple results in a " Alert: Preferred label languages must be unique" warning, even when the new language chosen is unique.  Try e.g. changing the language the last label for the mint of xanthus from Galician to German

**Comment by ewg118** [comment] 2019-04-17 14:25
Duplicate of #33

**Closed** 2019-04-17 14:25 UTC
